---
title: "Michealis-Menton equation and enzymic inhibition"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Michaelis-Menton equation

Calculations for the Michaelis-Menton equation quiz.



```{r}
df <- data.frame(S=c(1.0, 5.0, 10, 25, 50, 100, 250, 1000),
                 V=c(1.3, 5.0, 8.0, 13, 15, 17, 19, 20))
calcMM <- function(df) {
  stopifnot(all(c("S", "V") %in% colnames(df)))
  df$recS <- 1/df$S
  df$recV <- 1/df$V
  lmRes <- lm(recV ~ recS, data=df)
  Vmax <- 1/coef(lmRes)[1]
  Km <- Vmax * coef(lmRes)[2]
  res <- list(lmRes=lmRes, Vmax=Vmax, Km=Km)
  return(res)
}
```

```{r stats}
df$recS <- 1/df$S
mean(df$recS)
df$recV <- 1/df$V
mean(df$recV)
(lmRes <- lm(recV ~ recS, data=df))
(Vmax <- 1/coef(lmRes)[1])
(Km <- Vmax * coef(lmRes)[2])
```

## Ki and IC50

```{r}
inh <- data.frame(ic=c(0, 10, 100),
                  Km=c(0.9, 2.1, 9)*10^3)
calcKmKi <- function(km, ic) {
  inhLm <- lm(Km~ic)
  km <- coef(inhLm)[1]
  ki <- km/coef(inhLm)[2]
  res <- c("Km"=km, "Ki"=ki)
  return(res)
}
(inhLm <- lm(Km~ic, data=inh))
(km <- coef(inhLm)[1])
(ki <- km/coef(inhLm)[2])
```

```{r chengPrussoff}
ki <- function(ic50, s, km) {
  ic50 / (1 + s/km)
}

ki(50, 25*10^3, 5*10^3)

(lab1 <- ki(40, 3000, 750))
(lab2 <- ki(25, 2000, 750))
(lab3 <- ki(10, 200, 750))
```

```{r examination}
examDf <- data.frame(S=c(25, 50, 100, 150, 200),
                     V=c(0.240, 0.360, 0.530, 0.600, 0.610))
calcMM(examDf)
```

```{r examKmKi}
examKis <- ki(c(30, 100, 25, 50)*10^-3,
              c(500, 100, 10, 1000),
              2)

```

```{r examBinding}
ligandConc <- function(Kd, response) {
  response*Kd/(1-response)
}
ligandConc(8, 0.75)
250/(250+100)*.7
```

