---
title: "Chapter 7 (pharmacokinetics) exercise"
author: Jitao David Zhang
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```


```{r pk}
pkData <- data.frame(time=1:5,
                     Cp=c(75, 55, 41, 30, 22))

pkModel <- lm(log(Cp)~time, data=pkData)
(kel <- -coef(pkModel)[2])
(Cp0 <- exp(coef(pkModel)[1]))
(tHalf <- log(2)/kel)
```


```{r auc}
aucData <- data.frame(time=c(0.5, 1, 1.5, 2, 3, 4, 6, 8),
                      Cp=c(123, 101, 82, 67, 45, 30, 14,6))
(firstTrapezoid <- with(aucData,
                       (Cp[1]+Cp[2])*(time[2]-time[1])/2))
aucTrapezoid <- function(aucData, startInd=1) {
  with(aucData,
       (Cp[startInd]+Cp[startInd+1])/2*(time[startInd+1]-time[startInd]))
}
(trapezoid1 <- aucTrapezoid(aucData,1))
(trapezoid2 <- aucTrapezoid(aucData,2))
(trapezoid3 <- aucTrapezoid(aucData,3))
(trapezoid4 <- aucTrapezoid(aucData,4))
(trapezoid5 <- aucTrapezoid(aucData,5))
(trapezoid6 <- aucTrapezoid(aucData,6))
(trapezoid7 <- aucTrapezoid(aucData,7))
(trapezoid2to7 <- trapezoid2 + trapezoid3 + trapezoid4 + trapezoid5 + trapezoid6 + trapezoid7)

## estimate Cp0, using ln Cp, note that Cp0 needs transformation from log
firstLm <- with(aucData[1:2,],
                lm(log(Cp)~time))
Cp0 <- exp(coef(firstLm)[1])
(trapezoid0 <- (Cp0+aucData$Cp[1])/2*(aucData$time[1]-0))

## estimate the last area under curve
lastLm <- with(aucData[(nrow(aucData)-1):nrow(aucData),],
               lm(log(Cp)~time))
kel <- -coef(lastLm)[2]
(trapezoidLast <- aucData$Cp[nrow(aucData)]/kel)

## sum all trapezoid up
(trapazoidSum <- trapezoid0 + trapezoid1 + trapezoid2to7 + trapezoidLast)
```

```{r aucRefactor}
aucTrapezoids <- function(aucData) {
  stopifnot(all(c("time", "Cp") %in% colnames(aucData)))
  if(nrow(aucData)<=2) 
    stop("At least three points needed")
  ## from second to the last
  firstLm <- with(aucData[1:2,],
                  lm(log(Cp)~time))
  Cp0 <- exp(coef(firstLm)[1])
  (trapezoid0 <- (Cp0+aucData$Cp[1])/2*(aucData$time[1]-0))                 
  ## last
  lastLm <- with(aucData[(nrow(aucData)-1):nrow(aucData),],
               lm(log(Cp)~time))
  kel <- -coef(lastLm)[2]
  (trapezoidLast <- aucData$Cp[nrow(aucData)]/kel)
  ## between
  betweenInds <- 1:(nrow(aucData)-1)
  betweens <- sapply(betweenInds, function(i) {
    aucTrapezoid(aucData, i)
  })
  res <- c(trapezoid0, betweens, trapezoidLast)
  names(res) <- c("Trapezoid 0 based on estimated Cp0",
                  sprintf("trapezoid %d", betweenInds),
                  "Last trapezoid based on estimated k_el")
  return(res)
}
sum(aucTrapezoids(aucData))
```

```{r vd}
vdData <- data.frame(time=c(1,2,3,4,5),
                     Cp=c(21, 13, 8, 5, 3))
dose <- 1000
vdModel <- lm(log(Cp)~time, data=vdData)
## (kel <- -coef(vdModel)[2])
(Cp0 <- exp(coef(vdModel)[1]))
(vd <- dose/Cp0)
## (tHalf <- log(2)/kel)
```

